### PR TITLE
Rewrite README

### PR DESCRIPTION
**Pull request by chriscressman**
[Live preview](https://github.com/elastic/enterprise-search-sharepoint-server-connector/tree/chriscressman/readme)

### CODE REVIEW

**Review by artem-shelkovnikov — APPROVED** [review]
Looks great!

**Comment by praveen-elastic** [comment]
Looks great. I would like to add few suggestions: 
This version of the Connector is not supported for Elastic Enterprise Search versions 8.0 and above
In the field `sharepoint.host_url`, the port should be that of the web application in the SharePoint server where the site-collections are present and not of the Central Administration.

**Comment by praveen-elastic** [comment]
> I think it is supported by Enterprise Search 8.0+ versions - I've tested it there. @praveen-elastic can you elaborate more why it's not supported?

We recently discovered that Enterprise Search versions 8.0 and above do not have /permissions endpoint. Instead we'll have to use /external-identities as mentioned in issue  #41. Currently our connector uses /permissions endpoint

**Comment by chriscressman** [comment]
Thanks @praveen-elastic :+1: 

I applied those two changes.

**Review by serenachou — APPROVED** [review]
@chriscressman  honestly, this blows me away with how much better this is now.  I'm going to merge the changes now. My only suggestions right now is that I had an interesting call with a developer asking what they would need to see in a readme like this to understand whether they want to pursue customization - they said they would like to see a full catalog of capabilities and how this relates. I'd recommend that we add a link to the "content source" overview page (or the future version of it)  to talk about how we have a nice default catalog before customers commit to deploying this. Then, also the second recommendation is to add a link to the python enterprise search clients page https://www.elastic.co/guide/en/enterprise-search-clients/python/current/index.html as there can be the potential for breaking changes that occur based on api changes.

**Pull request merged**
